info:
  app:
    name: "dhaine-banking"
    description: "Dhaine Banking Service"
    version: "0.0.1-SNAPSHOT"

spring:
  application:
    name: dhaine-banking
  profiles:
    active: "dev"


springdoc:
  swagger-ui:
    path: "/documentation/doc-ui.html"
    url: "/documentation/v3/api-docs"
    disable-swagger-default-url: true
    configUrl: "/documentation/v3/api-docs/swagger-config"
    operationsSorter: "method"
    tagsSorter: "alpha"
  api-docs:
    path: "/documentation/v3/api-docs"

logging:
  file:
    name: dhaine-banking-service.log